"""
Django settings for proyecto project.

Generated by 'django-admin startproject' using Django 4.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-_c+z%#d(5ugsrfz&v413bz@9g$*7w_dy=k3ie(*$4z&5#m5e=%'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'tasks',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'proyecto.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'proyecto.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "BDREDIS",
        "USER": "postgres",
        "PASSWORD": "123456",
        "HOST": "127.0.0.1",
        "PORT": "5432",
    }
}

# Tiempo de vida de la cookie de sesión en segundos (300 segundos = 5 minutos)
SESSION_COOKIE_AGE = 120  # expire de redis
# Indica si la sesión debe expirar al cerrar el navegador. False significa que la sesión persiste.
SESSION_EXPIRE_AT_BROWSER_CLOSE = False  

# Configuración de caché para Django
CACHES = {
    "default": {  # Configuración de la caché por defecto
        "BACKEND": "django_redis.cache.RedisCache",  # Usa django-redis como backend de caché
        "LOCATION": "redis://127.0.0.1:6379/1",  # Dirección del servidor Redis (puerto 6379, base de datos 1)
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",  # Clase cliente para manejar conexiones Redis
            "SERIALIZER": "django_redis.serializers.json.JSONSerializer",  # Serializa los datos en formato JSON
            "COMPRESSOR": "django_redis.compressors.identity.IdentityCompressor",  # Desactiva la compresión de datos
            "COMPRESS_MIN_LEN": 0,  # Fuerza que nunca se compriman los datos, independientemente de su tamaño
        }
    }
}
# Configura el motor de sesiones para usar la caché como almacenamiento
SESSION_ENGINE = "django.contrib.sessions.backends.cache"
# Especifica el alias de la caché que se usará para las sesiones (en este caso, "default")
SESSION_CACHE_ALIAS = "default"
# Define el serializador para las sesiones, en este caso JSON
SESSION_SERIALIZER = 'django.contrib.sessions.serializers.JSONSerializer'





# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'

LOGIN_URL = '/signin/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
